apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-desafio-devops
  namespace: desafio-devops

spec:
  secretName: secret-tls
  renewBefore: 240h
  duration: 2160h
  commonName: api.app.devopsbr.com.br
  dnsNames:
  - api.app.devopsbr.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer