apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: juniorflax@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
       ingress:
         class: nginx