apiVersion: v1
kind: Service
metadata:
  name: dasafio-devops-service
  namespace: desafio-devops
spec:
  type: LoadBalancer
  selector:
    app: desafio-devops
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000