name: Testes na Aplicação

on:
  push:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4.1.2
      
    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10.12'
      
    - name: Instalar Dependências
      uses: py-actions/py-dependency-install@v4
      with:
        path: ./app/requirements.txt
        
    - name: Iniciar Servidor da Aplicação
      working-directory: app
      run: |
        gunicorn --daemon --bind localhost:8000 api:app
        sleep 5  # Espera alguns segundos para que o servidor inicie
        
    - name: Testar Aplicação
      run: |
        curl -sv localhost:8000/api/comment/new -X POST -H 'Content-Type: application/json' -d '{"email":"alice@example.com","comment":"first post!","content_id":1}'
        curl -sv localhost:8000/api/comment/list/1
  
    - name: Build the Docker image
      working-directory: app
      run: docker build . --file Dockerfile --tag ${{ secrets.USER_DOCKERHUB }}/desafio-devops:v0.2

    - name: Login DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.USER_DOCKERHUB }}
        password: ${{ secrets.PASS_DOCKERHUB }}
        
    - name: Push the Docker image
      working-directory: app
      run: docker push ${{ secrets.USER_DOCKERHUB }}/desafio-devops:v0.2       
